name: spacyface
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.7
  - pip=19.0.3
  - h5py
  - spacy
  - regex
  - numpy
  - pytorch
  - sacremoses
  - pip:
    - sentencepiece
    - transformers
